name: Testing

on:
  push:
    branches: [master, submaster]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - run: npm i
      - run: npm test

        